export const medals = [
  {
    athlete: 'THOMPSON, Richard',
    country: 'TRI',
    sex: 'Men',
    event: '100m',
    medal: 'Silver',
    id: 8,
  },
  {
    athlete: 'BLEDMAN, Keston',
    country: 'TRI',
    sex: 'Men',
    event: '4x100m relay',
    medal: 'Silver',
    id: 62,
  },
  {
    athlete: 'BURNS, Marc',
    country: 'TRI',
    sex: 'Men',
    event: '4x100m relay',
    medal: 'Silver',
    id: 63,
  },
  {
    athlete: 'CALLENDER, Emmanuel',
    country: 'TRI',
    sex: 'Men',
    event: '4x100m relay',
    medal: 'Silver',
    id: 64,
  },
  {
    athlete: 'THOMPSON, Richard',
    country: 'TRI',
    sex: 'Men',
    event: '4x100m relay',
    medal: 'Silver',
    id: 65,
  },
  {
    athlete: 'BAIN, Andretti',
    country: 'BAH',
    sex: 'Men',
    event: '4x400m relay',
    medal: 'Silver',
    id: 86,
  },
  {
    athlete: 'BROWN, Christopher',
    country: 'BAH',
    sex: 'Men',
    event: '4x400m relay',
    medal: 'Silver',
    id: 87,
  },
  {
    athlete: 'MATHIEU, Michael',
    country: 'BAH',
    sex: 'Men',
    event: '4x400m relay',
    medal: 'Silver',
    id: 88,
  },
  {
    athlete: 'WILLIAMS, Andrae',
    country: 'BAH',
    sex: 'Men',
    event: '4x400m relay',
    medal: 'Silver',
    id: 89,
  },
  {
    athlete: 'SANDS, Leevan',
    country: 'BAH',
    sex: 'Men',
    event: 'triple jump',
    medal: 'Bronze',
    id: 171,
  },
  {
    athlete: 'MCLELLAN, Sally',
    country: 'AUS',
    sex: 'Women',
    event: '100m hurdles',
    medal: 'Silver',
    id: 14,
  },
  {
    athlete: 'TALLENT, Jared',
    country: 'AUS',
    sex: 'Men',
    event: '20km walk',
    medal: 'Bronze',
    id: 33,
  },
  {
    athlete: 'TALLENT, Jared',
    country: 'AUS',
    sex: 'Men',
    event: '50km walk',
    medal: 'Silver',
    id: 110,
  },
  {
    athlete: 'HOOKER, Steve',
    country: 'AUS',
    sex: 'Men',
    event: 'pole vault',
    medal: 'Gold',
    id: 160,
  },
  {
    athlete: 'MALACHOWSKI, Piotr',
    country: 'POL',
    sex: 'Men',
    event: 'discus throw',
    medal: 'Silver',
    id: 122,
  },
  {
    athlete: 'MAJEWSKI, Tomasz',
    country: 'POL',
    sex: 'Men',
    event: 'shot put',
    medal: 'Gold',
    id: 166,
  },
  {
    athlete: 'LOPES-SCHLIEP, Priscilla',
    country: 'CAN',
    sex: 'Women',
    event: '100m hurdles',
    medal: 'Bronze',
    id: 12,
  },
  {
    athlete: 'DEVETZI, Hrysopiyi',
    country: 'GRE',
    sex: 'Women',
    event: 'triple jump',
    medal: 'Bronze',
    id: 174,
  },
];

export const countries = [
  {
    medals: [
      {
        athlete: 'THOMPSON, Richard',
        country: 'TRI',
        sex: 'Men',
        event: '100m',
        medal: 'Silver',
        id: 8,
      },
      {
        athlete: 'BLEDMAN, Keston',
        country: 'TRI',
        sex: 'Men',
        event: '4x100m relay',
        medal: 'Silver',
        id: 62,
      },
      {
        athlete: 'BURNS, Marc',
        country: 'TRI',
        sex: 'Men',
        event: '4x100m relay',
        medal: 'Silver',
        id: 63,
      },
      {
        athlete: 'CALLENDER, Emmanuel',
        country: 'TRI',
        sex: 'Men',
        event: '4x100m relay',
        medal: 'Silver',
        id: 64,
      },
      {
        athlete: 'THOMPSON, Richard',
        country: 'TRI',
        sex: 'Men',
        event: '4x100m relay',
        medal: 'Silver',
        id: 65,
      },
    ],
    goldCount: 0,
    silverCount: 5,
    bronzeCount: 0,
    totalCount: 5,
    code: 'TRI',
  },
  {
    medals: [
      {
        athlete: 'BAIN, Andretti',
        country: 'BAH',
        sex: 'Men',
        event: '4x400m relay',
        medal: 'Silver',
        id: 86,
      },
      {
        athlete: 'BROWN, Christopher',
        country: 'BAH',
        sex: 'Men',
        event: '4x400m relay',
        medal: 'Silver',
        id: 87,
      },
      {
        athlete: 'MATHIEU, Michael',
        country: 'BAH',
        sex: 'Men',
        event: '4x400m relay',
        medal: 'Silver',
        id: 88,
      },
      {
        athlete: 'WILLIAMS, Andrae',
        country: 'BAH',
        sex: 'Men',
        event: '4x400m relay',
        medal: 'Silver',
        id: 89,
      },
      {
        athlete: 'SANDS, Leevan',
        country: 'BAH',
        sex: 'Men',
        event: 'triple jump',
        medal: 'Bronze',
        id: 171,
      },
    ],
    goldCount: 0,
    silverCount: 4,
    bronzeCount: 1,
    totalCount: 5,
    code: 'BAH',
    name: 'Bahamas',
    emoji: '🇧🇸',
  },
  {
    medals: [
      {
        athlete: 'MCLELLAN, Sally',
        country: 'AUS',
        sex: 'Women',
        event: '100m hurdles',
        medal: 'Silver',
        id: 14,
      },
      {
        athlete: 'TALLENT, Jared',
        country: 'AUS',
        sex: 'Men',
        event: '20km walk',
        medal: 'Bronze',
        id: 33,
      },
      {
        athlete: 'TALLENT, Jared',
        country: 'AUS',
        sex: 'Men',
        event: '50km walk',
        medal: 'Silver',
        id: 110,
      },
      {
        athlete: 'HOOKER, Steve',
        country: 'AUS',
        sex: 'Men',
        event: 'pole vault',
        medal: 'Gold',
        id: 160,
      },
    ],
    goldCount: 1,
    silverCount: 2,
    bronzeCount: 1,
    totalCount: 4,
    code: 'AUS',
    name: 'Australia',
    emoji: '🇦🇺',
  },
  {
    medals: [
      {
        athlete: 'MALACHOWSKI, Piotr',
        country: 'POL',
        sex: 'Men',
        event: 'discus throw',
        medal: 'Silver',
        id: 122,
      },
      {
        athlete: 'MAJEWSKI, Tomasz',
        country: 'POL',
        sex: 'Men',
        event: 'shot put',
        medal: 'Gold',
        id: 166,
      },
    ],
    goldCount: 1,
    silverCount: 1,
    bronzeCount: 0,
    totalCount: 2,
    code: 'POL',
    name: 'Poland',
    emoji: '🇵🇱',
  },
  {
    medals: [
      {
        athlete: 'LOPES-SCHLIEP, Priscilla',
        country: 'CAN',
        sex: 'Women',
        event: '100m hurdles',
        medal: 'Bronze',
        id: 12,
      },
    ],
    goldCount: 0,
    silverCount: 0,
    bronzeCount: 1,
    totalCount: 1,
    code: 'CAN',
    name: 'Canada',
    emoji: '🇨🇦',
  },
  {
    medals: [
      {
        athlete: 'DEVETZI, Hrysopiyi',
        country: 'GRE',
        sex: 'Women',
        event: 'triple jump',
        medal: 'Bronze',
        id: 174,
      },
    ],
    goldCount: 0,
    silverCount: 0,
    bronzeCount: 1,
    totalCount: 1,
    code: 'GRE',
    name: 'Greece',
    emoji: '🇬🇷',
  },
];

function shuffle(a) {
  for (let i = a.length; i; i -= 1) {
    const j = Math.floor(Math.random() * i);
    // eslint-disable-next-line no-param-reassign
    [a[i - 1], a[j]] = [a[j], a[i - 1]];
  }
}

export const shuffledCountries = countries.slice();
shuffle(shuffledCountries);
